export interface CountryOption {
  id: string;
  label: string;
  labelFr: string;
  icon?: string;
}

// Tri : Tunisie / Algerie / Maroc / France en tete (marches prioritaires GoConnexions),
// puis reste du monde par ordre alphabetique (nom FR).
export const COUNTRIES: CountryOption[] = [
  { id: 'TN', label: "Tunisia", labelFr: "Tunisie", icon: '🇹🇳' },
  { id: 'DZ', label: "Algeria", labelFr: "Algérie", icon: '🇩🇿' },
  { id: 'MA', label: "Morocco", labelFr: "Maroc", icon: '🇲🇦' },
  { id: 'FR', label: "France", labelFr: "France", icon: '🇫🇷' },
  { id: 'CA', label: "Canada", labelFr: "Canada", icon: '🇨🇦' },
  { id: 'BE', label: "Belgium", labelFr: "Belgique", icon: '🇧🇪' },
  { id: 'CH', label: "Switzerland", labelFr: "Suisse", icon: '🇨🇭' },
  { id: 'AF', label: "Afghanistan", labelFr: "Afghanistan", icon: '🇦🇫' },
  { id: 'ZA', label: "South Africa", labelFr: "Afrique du Sud", icon: '🇿🇦' },
  { id: 'AL', label: "Albania", labelFr: "Albanie", icon: '🇦🇱' },
  { id: 'DE', label: "Germany", labelFr: "Allemagne", icon: '🇩🇪' },
  { id: 'AD', label: "Andorra", labelFr: "Andorre", icon: '🇦🇩' },
  { id: 'AO', label: "Angola", labelFr: "Angola", icon: '🇦🇴' },
  { id: 'AG', label: "Antigua & Barbuda", labelFr: "Antigua-et-Barbuda", icon: '🇦🇬' },
  { id: 'SA', label: "Saudi Arabia", labelFr: "Arabie saoudite", icon: '🇸🇦' },
  { id: 'AR', label: "Argentina", labelFr: "Argentine", icon: '🇦🇷' },
  { id: 'AM', label: "Armenia", labelFr: "Arménie", icon: '🇦🇲' },
  { id: 'AU', label: "Australia", labelFr: "Australie", icon: '🇦🇺' },
  { id: 'AT', label: "Austria", labelFr: "Autriche", icon: '🇦🇹' },
  { id: 'AZ', label: "Azerbaijan", labelFr: "Azerbaïdjan", icon: '🇦🇿' },
  { id: 'BS', label: "Bahamas", labelFr: "Bahamas", icon: '🇧🇸' },
  { id: 'BH', label: "Bahrain", labelFr: "Bahreïn", icon: '🇧🇭' },
  { id: 'BD', label: "Bangladesh", labelFr: "Bangladesh", icon: '🇧🇩' },
  { id: 'BB', label: "Barbados", labelFr: "Barbade", icon: '🇧🇧' },
  { id: 'BZ', label: "Belize", labelFr: "Belize", icon: '🇧🇿' },
  { id: 'BJ', label: "Benin", labelFr: "Bénin", icon: '🇧🇯' },
  { id: 'BT', label: "Bhutan", labelFr: "Bhoutan", icon: '🇧🇹' },
  { id: 'BY', label: "Belarus", labelFr: "Biélorussie", icon: '🇧🇾' },
  { id: 'BO', label: "Bolivia", labelFr: "Bolivie", icon: '🇧🇴' },
  { id: 'BA', label: "Bosnia & Herzegovina", labelFr: "Bosnie-Herzégovine", icon: '🇧🇦' },
  { id: 'BW', label: "Botswana", labelFr: "Botswana", icon: '🇧🇼' },
  { id: 'BR', label: "Brazil", labelFr: "Brésil", icon: '🇧🇷' },
  { id: 'BN', label: "Brunei", labelFr: "Brunei", icon: '🇧🇳' },
  { id: 'BG', label: "Bulgaria", labelFr: "Bulgarie", icon: '🇧🇬' },
  { id: 'BF', label: "Burkina Faso", labelFr: "Burkina Faso", icon: '🇧🇫' },
  { id: 'BI', label: "Burundi", labelFr: "Burundi", icon: '🇧🇮' },
  { id: 'KH', label: "Cambodia", labelFr: "Cambodge", icon: '🇰🇭' },
  { id: 'CM', label: "Cameroon", labelFr: "Cameroun", icon: '🇨🇲' },
  { id: 'CV', label: "Cape Verde", labelFr: "Cap-Vert", icon: '🇨🇻' },
  { id: 'CL', label: "Chile", labelFr: "Chili", icon: '🇨🇱' },
  { id: 'CN', label: "China", labelFr: "Chine", icon: '🇨🇳' },
  { id: 'CY', label: "Cyprus", labelFr: "Chypre", icon: '🇨🇾' },
  { id: 'CO', label: "Colombia", labelFr: "Colombie", icon: '🇨🇴' },
  { id: 'KM', label: "Comoros", labelFr: "Comores", icon: '🇰🇲' },
  { id: 'CG', label: "Congo - Brazzaville", labelFr: "Congo-Brazzaville", icon: '🇨🇬' },
  { id: 'CD', label: "Congo - Kinshasa", labelFr: "Congo-Kinshasa", icon: '🇨🇩' },
  { id: 'KP', label: "North Korea", labelFr: "Corée du Nord", icon: '🇰🇵' },
  { id: 'KR', label: "South Korea", labelFr: "Corée du Sud", icon: '🇰🇷' },
  { id: 'CR', label: "Costa Rica", labelFr: "Costa Rica", icon: '🇨🇷' },
  { id: 'CI', label: "Côte d’Ivoire", labelFr: "Côte d’Ivoire", icon: '🇨🇮' },
  { id: 'HR', label: "Croatia", labelFr: "Croatie", icon: '🇭🇷' },
  { id: 'CU', label: "Cuba", labelFr: "Cuba", icon: '🇨🇺' },
  { id: 'DK', label: "Denmark", labelFr: "Danemark", icon: '🇩🇰' },
  { id: 'DJ', label: "Djibouti", labelFr: "Djibouti", icon: '🇩🇯' },
  { id: 'DM', label: "Dominica", labelFr: "Dominique", icon: '🇩🇲' },
  { id: 'EG', label: "Egypt", labelFr: "Égypte", icon: '🇪🇬' },
  { id: 'AE', label: "United Arab Emirates", labelFr: "Émirats arabes unis", icon: '🇦🇪' },
  { id: 'EC', label: "Ecuador", labelFr: "Équateur", icon: '🇪🇨' },
  { id: 'ER', label: "Eritrea", labelFr: "Érythrée", icon: '🇪🇷' },
  { id: 'ES', label: "Spain", labelFr: "Espagne", icon: '🇪🇸' },
  { id: 'EE', label: "Estonia", labelFr: "Estonie", icon: '🇪🇪' },
  { id: 'SZ', label: "Eswatini", labelFr: "Eswatini", icon: '🇸🇿' },
  { id: 'VA', label: "Vatican City", labelFr: "État de la Cité du Vatican", icon: '🇻🇦' },
  { id: 'US', label: "United States", labelFr: "États-Unis", icon: '🇺🇸' },
  { id: 'ET', label: "Ethiopia", labelFr: "Éthiopie", icon: '🇪🇹' },
  { id: 'FJ', label: "Fiji", labelFr: "Fidji", icon: '🇫🇯' },
  { id: 'FI', label: "Finland", labelFr: "Finlande", icon: '🇫🇮' },
  { id: 'GA', label: "Gabon", labelFr: "Gabon", icon: '🇬🇦' },
  { id: 'GM', label: "Gambia", labelFr: "Gambie", icon: '🇬🇲' },
  { id: 'GE', label: "Georgia", labelFr: "Géorgie", icon: '🇬🇪' },
  { id: 'GH', label: "Ghana", labelFr: "Ghana", icon: '🇬🇭' },
  { id: 'GR', label: "Greece", labelFr: "Grèce", icon: '🇬🇷' },
  { id: 'GD', label: "Grenada", labelFr: "Grenade", icon: '🇬🇩' },
  { id: 'GT', label: "Guatemala", labelFr: "Guatemala", icon: '🇬🇹' },
  { id: 'GN', label: "Guinea", labelFr: "Guinée", icon: '🇬🇳' },
  { id: 'GQ', label: "Equatorial Guinea", labelFr: "Guinée équatoriale", icon: '🇬🇶' },
  { id: 'GW', label: "Guinea-Bissau", labelFr: "Guinée-Bissau", icon: '🇬🇼' },
  { id: 'GY', label: "Guyana", labelFr: "Guyana", icon: '🇬🇾' },
  { id: 'HT', label: "Haiti", labelFr: "Haïti", icon: '🇭🇹' },
  { id: 'HN', label: "Honduras", labelFr: "Honduras", icon: '🇭🇳' },
  { id: 'HU', label: "Hungary", labelFr: "Hongrie", icon: '🇭🇺' },
  { id: 'MH', label: "Marshall Islands", labelFr: "Îles Marshall", icon: '🇲🇭' },
  { id: 'SB', label: "Solomon Islands", labelFr: "Îles Salomon", icon: '🇸🇧' },
  { id: 'IN', label: "India", labelFr: "Inde", icon: '🇮🇳' },
  { id: 'ID', label: "Indonesia", labelFr: "Indonésie", icon: '🇮🇩' },
  { id: 'IQ', label: "Iraq", labelFr: "Irak", icon: '🇮🇶' },
  { id: 'IR', label: "Iran", labelFr: "Iran", icon: '🇮🇷' },
  { id: 'IE', label: "Ireland", labelFr: "Irlande", icon: '🇮🇪' },
  { id: 'IS', label: "Iceland", labelFr: "Islande", icon: '🇮🇸' },
  { id: 'IL', label: "Israel", labelFr: "Israël", icon: '🇮🇱' },
  { id: 'IT', label: "Italy", labelFr: "Italie", icon: '🇮🇹' },
  { id: 'JM', label: "Jamaica", labelFr: "Jamaïque", icon: '🇯🇲' },
  { id: 'JP', label: "Japan", labelFr: "Japon", icon: '🇯🇵' },
  { id: 'JO', label: "Jordan", labelFr: "Jordanie", icon: '🇯🇴' },
  { id: 'KZ', label: "Kazakhstan", labelFr: "Kazakhstan", icon: '🇰🇿' },
  { id: 'KE', label: "Kenya", labelFr: "Kenya", icon: '🇰🇪' },
  { id: 'KG', label: "Kyrgyzstan", labelFr: "Kirghizstan", icon: '🇰🇬' },
  { id: 'KI', label: "Kiribati", labelFr: "Kiribati", icon: '🇰🇮' },
  { id: 'KW', label: "Kuwait", labelFr: "Koweït", icon: '🇰🇼' },
  { id: 'LA', label: "Laos", labelFr: "Laos", icon: '🇱🇦' },
  { id: 'LS', label: "Lesotho", labelFr: "Lesotho", icon: '🇱🇸' },
  { id: 'LV', label: "Latvia", labelFr: "Lettonie", icon: '🇱🇻' },
  { id: 'LB', label: "Lebanon", labelFr: "Liban", icon: '🇱🇧' },
  { id: 'LR', label: "Liberia", labelFr: "Liberia", icon: '🇱🇷' },
  { id: 'LY', label: "Libya", labelFr: "Libye", icon: '🇱🇾' },
  { id: 'LI', label: "Liechtenstein", labelFr: "Liechtenstein", icon: '🇱🇮' },
  { id: 'LT', label: "Lithuania", labelFr: "Lituanie", icon: '🇱🇹' },
  { id: 'LU', label: "Luxembourg", labelFr: "Luxembourg", icon: '🇱🇺' },
  { id: 'MK', label: "North Macedonia", labelFr: "Macédoine du Nord", icon: '🇲🇰' },
  { id: 'MG', label: "Madagascar", labelFr: "Madagascar", icon: '🇲🇬' },
  { id: 'MY', label: "Malaysia", labelFr: "Malaisie", icon: '🇲🇾' },
  { id: 'MW', label: "Malawi", labelFr: "Malawi", icon: '🇲🇼' },
  { id: 'MV', label: "Maldives", labelFr: "Maldives", icon: '🇲🇻' },
  { id: 'ML', label: "Mali", labelFr: "Mali", icon: '🇲🇱' },
  { id: 'MT', label: "Malta", labelFr: "Malte", icon: '🇲🇹' },
  { id: 'MU', label: "Mauritius", labelFr: "Maurice", icon: '🇲🇺' },
  { id: 'MR', label: "Mauritania", labelFr: "Mauritanie", icon: '🇲🇷' },
  { id: 'MX', label: "Mexico", labelFr: "Mexique", icon: '🇲🇽' },
  { id: 'FM', label: "Micronesia", labelFr: "Micronésie", icon: '🇫🇲' },
  { id: 'MD', label: "Moldova", labelFr: "Moldavie", icon: '🇲🇩' },
  { id: 'MC', label: "Monaco", labelFr: "Monaco", icon: '🇲🇨' },
  { id: 'MN', label: "Mongolia", labelFr: "Mongolie", icon: '🇲🇳' },
  { id: 'ME', label: "Montenegro", labelFr: "Monténégro", icon: '🇲🇪' },
  { id: 'MZ', label: "Mozambique", labelFr: "Mozambique", icon: '🇲🇿' },
  { id: 'MM', label: "Myanmar (Burma)", labelFr: "Myanmar (Birmanie)", icon: '🇲🇲' },
  { id: 'NA', label: "Namibia", labelFr: "Namibie", icon: '🇳🇦' },
  { id: 'NR', label: "Nauru", labelFr: "Nauru", icon: '🇳🇷' },
  { id: 'NP', label: "Nepal", labelFr: "Népal", icon: '🇳🇵' },
  { id: 'NI', label: "Nicaragua", labelFr: "Nicaragua", icon: '🇳🇮' },
  { id: 'NE', label: "Niger", labelFr: "Niger", icon: '🇳🇪' },
  { id: 'NG', label: "Nigeria", labelFr: "Nigeria", icon: '🇳🇬' },
  { id: 'NO', label: "Norway", labelFr: "Norvège", icon: '🇳🇴' },
  { id: 'NZ', label: "New Zealand", labelFr: "Nouvelle-Zélande", icon: '🇳🇿' },
  { id: 'OM', label: "Oman", labelFr: "Oman", icon: '🇴🇲' },
  { id: 'UG', label: "Uganda", labelFr: "Ouganda", icon: '🇺🇬' },
  { id: 'UZ', label: "Uzbekistan", labelFr: "Ouzbékistan", icon: '🇺🇿' },
  { id: 'PK', label: "Pakistan", labelFr: "Pakistan", icon: '🇵🇰' },
  { id: 'PW', label: "Palau", labelFr: "Palaos", icon: '🇵🇼' },
  { id: 'PA', label: "Panama", labelFr: "Panama", icon: '🇵🇦' },
  { id: 'PG', label: "Papua New Guinea", labelFr: "Papouasie-Nouvelle-Guinée", icon: '🇵🇬' },
  { id: 'PY', label: "Paraguay", labelFr: "Paraguay", icon: '🇵🇾' },
  { id: 'NL', label: "Netherlands", labelFr: "Pays-Bas", icon: '🇳🇱' },
  { id: 'PE', label: "Peru", labelFr: "Pérou", icon: '🇵🇪' },
  { id: 'PH', label: "Philippines", labelFr: "Philippines", icon: '🇵🇭' },
  { id: 'PL', label: "Poland", labelFr: "Pologne", icon: '🇵🇱' },
  { id: 'PT', label: "Portugal", labelFr: "Portugal", icon: '🇵🇹' },
  { id: 'QA', label: "Qatar", labelFr: "Qatar", icon: '🇶🇦' },
  { id: 'CF', label: "Central African Republic", labelFr: "République centrafricaine", icon: '🇨🇫' },
  { id: 'DO', label: "Dominican Republic", labelFr: "République dominicaine", icon: '🇩🇴' },
  { id: 'RO', label: "Romania", labelFr: "Roumanie", icon: '🇷🇴' },
  { id: 'GB', label: "United Kingdom", labelFr: "Royaume-Uni", icon: '🇬🇧' },
  { id: 'RU', label: "Russia", labelFr: "Russie", icon: '🇷🇺' },
  { id: 'RW', label: "Rwanda", labelFr: "Rwanda", icon: '🇷🇼' },
  { id: 'KN', label: "St. Kitts & Nevis", labelFr: "Saint-Christophe-et-Niévès", icon: '🇰🇳' },
  { id: 'SM', label: "San Marino", labelFr: "Saint-Marin", icon: '🇸🇲' },
  { id: 'VC', label: "St. Vincent & Grenadines", labelFr: "Saint-Vincent-et-les Grenadines", icon: '🇻🇨' },
  { id: 'LC', label: "St. Lucia", labelFr: "Sainte-Lucie", icon: '🇱🇨' },
  { id: 'SV', label: "El Salvador", labelFr: "Salvador", icon: '🇸🇻' },
  { id: 'WS', label: "Samoa", labelFr: "Samoa", icon: '🇼🇸' },
  { id: 'ST', label: "São Tomé & Príncipe", labelFr: "Sao Tomé-et-Principe", icon: '🇸🇹' },
  { id: 'SN', label: "Senegal", labelFr: "Sénégal", icon: '🇸🇳' },
  { id: 'RS', label: "Serbia", labelFr: "Serbie", icon: '🇷🇸' },
  { id: 'SC', label: "Seychelles", labelFr: "Seychelles", icon: '🇸🇨' },
  { id: 'SL', label: "Sierra Leone", labelFr: "Sierra Leone", icon: '🇸🇱' },
  { id: 'SG', label: "Singapore", labelFr: "Singapour", icon: '🇸🇬' },
  { id: 'SK', label: "Slovakia", labelFr: "Slovaquie", icon: '🇸🇰' },
  { id: 'SI', label: "Slovenia", labelFr: "Slovénie", icon: '🇸🇮' },
  { id: 'SO', label: "Somalia", labelFr: "Somalie", icon: '🇸🇴' },
  { id: 'SD', label: "Sudan", labelFr: "Soudan", icon: '🇸🇩' },
  { id: 'SS', label: "South Sudan", labelFr: "Soudan du Sud", icon: '🇸🇸' },
  { id: 'LK', label: "Sri Lanka", labelFr: "Sri Lanka", icon: '🇱🇰' },
  { id: 'SE', label: "Sweden", labelFr: "Suède", icon: '🇸🇪' },
  { id: 'SR', label: "Suriname", labelFr: "Suriname", icon: '🇸🇷' },
  { id: 'SY', label: "Syria", labelFr: "Syrie", icon: '🇸🇾' },
  { id: 'TJ', label: "Tajikistan", labelFr: "Tadjikistan", icon: '🇹🇯' },
  { id: 'TW', label: "Taiwan", labelFr: "Taïwan", icon: '🇹🇼' },
  { id: 'TZ', label: "Tanzania", labelFr: "Tanzanie", icon: '🇹🇿' },
  { id: 'TD', label: "Chad", labelFr: "Tchad", icon: '🇹🇩' },
  { id: 'CZ', label: "Czechia", labelFr: "Tchéquie", icon: '🇨🇿' },
  { id: 'PS', label: "Palestinian Territories", labelFr: "Territoires palestiniens", icon: '🇵🇸' },
  { id: 'TH', label: "Thailand", labelFr: "Thaïlande", icon: '🇹🇭' },
  { id: 'TL', label: "Timor-Leste", labelFr: "Timor oriental", icon: '🇹🇱' },
  { id: 'TG', label: "Togo", labelFr: "Togo", icon: '🇹🇬' },
  { id: 'TO', label: "Tonga", labelFr: "Tonga", icon: '🇹🇴' },
  { id: 'TT', label: "Trinidad & Tobago", labelFr: "Trinité-et-Tobago", icon: '🇹🇹' },
  { id: 'TM', label: "Turkmenistan", labelFr: "Turkménistan", icon: '🇹🇲' },
  { id: 'TR', label: "Türkiye", labelFr: "Turquie", icon: '🇹🇷' },
  { id: 'TV', label: "Tuvalu", labelFr: "Tuvalu", icon: '🇹🇻' },
  { id: 'UA', label: "Ukraine", labelFr: "Ukraine", icon: '🇺🇦' },
  { id: 'UY', label: "Uruguay", labelFr: "Uruguay", icon: '🇺🇾' },
  { id: 'VU', label: "Vanuatu", labelFr: "Vanuatu", icon: '🇻🇺' },
  { id: 'VE', label: "Venezuela", labelFr: "Venezuela", icon: '🇻🇪' },
  { id: 'VN', label: "Vietnam", labelFr: "Viêt Nam", icon: '🇻🇳' },
  { id: 'YE', label: "Yemen", labelFr: "Yémen", icon: '🇾🇪' },
  { id: 'ZM', label: "Zambia", labelFr: "Zambie", icon: '🇿🇲' },
  { id: 'ZW', label: "Zimbabwe", labelFr: "Zimbabwe", icon: '🇿🇼' },
];
