export const INITIAL_INDUSTRIES = [
  { id: 'trainer_coach', labelEn: 'Trainer / Coach', labelFr: 'Formateur / Coach' },
  { id: 'web_developer', labelEn: 'Web Developer', labelFr: 'Développeur Web' },
  { id: 'mobile_developer', labelEn: 'Mobile Developer', labelFr: 'Développeur Mobile' },
  { id: 'software_engineer', labelEn: 'Software Engineer', labelFr: 'Ingénieur Logiciel' },
  { id: 'content_creator', labelEn: 'Content Creator', labelFr: 'Créateur de Contenu' },
  { id: 'graphic_designer', labelEn: 'Graphic Designer', labelFr: 'Graphiste / Designer' },
  { id: 'digital_marketing', labelEn: 'Digital Marketing', labelFr: 'Marketing Digital' },
  { id: 'social_media_manager', labelEn: 'Social Media Manager', labelFr: 'Community Manager' },
  { id: 'photographer', labelEn: 'Photographer', labelFr: 'Photographe' },
  { id: 'videographer', labelEn: 'Videographer', labelFr: 'Vidéaste' },
  { id: 'consultant', labelEn: 'Consultant', labelFr: 'Consultant' },
  { id: 'accountant', labelEn: 'Accountant', labelFr: 'Comptable' },
  { id: 'lawyer', labelEn: 'Lawyer', labelFr: 'Avocat / Juriste' },
  { id: 'real_estate', labelEn: 'Real Estate', labelFr: 'Immobilier' },
  { id: 'health_wellness', labelEn: 'Health & Wellness', labelFr: 'Santé & Bien-être' },
  { id: 'education', labelEn: 'Education', labelFr: 'Éducation' },
  { id: 'construction', labelEn: 'Construction', labelFr: 'Bâtiment / Construction' },
  { id: 'ecommerce', labelEn: 'E-commerce', labelFr: 'E-commerce' },
  { id: 'retail', labelEn: 'Retail', labelFr: 'Commerce de détail' },
  { id: 'restaurant_food', labelEn: 'Restaurant / Food Services', labelFr: 'Restauration / Alimentation' },
  { id: 'beauty_cosmetics', labelEn: 'Beauty & Cosmetics', labelFr: 'Beauté & Cosmétique' },
  { id: 'cleaning_services', labelEn: 'Cleaning Services', labelFr: 'Services de nettoyage' },
  { id: 'transportation', labelEn: 'Transportation', labelFr: 'Transport / Logistique' },
  { id: 'event_planning', labelEn: 'Event Planning', labelFr: 'Événementiel' },
  { id: 'other', labelEn: 'Other', labelFr: 'Autre' },
] as const;

export const INDUSTRY_VALUES = INITIAL_INDUSTRIES.map((i) => i.labelEn);
